### ISSUE TITLE
When test-con2 is run in a console, it should act more like a console app!

### ISSUE THREAD

**Issue by geoffmcl** [geoffmcl/test-console#2]
At present certain redirections are correctly handled when SUBSYSTEM:windows is used, for `test-con2`, and it is run in a console :-

```
> test-con2 > temp1.txt 2>&1
```

This works fine. That is **all** the `stdout` and `stderr` text is found in the `temp1.txt` file... good!

But 3 other forms are not fully correct - messages are lost...

```
> test-con2 > temp2.txt
> test-con2 2> temp3.txt
> test-con2 
```

While in the first two, the appropriate `stdout` in the first, and `stderr` in the second, correctly arrive in the file, **BUT** in all 3 cases, **no** output is seen in the console, as would happen if it was a subsystem:console app...

Can this be improved?

**Comment by geoffmcl** [comment]
Well, added checking of the state of both `stdout` and `stderr` separately, and using `freopen` when a channel is not already redirected, seems to get it very close to its subsystem:console counter part...

But in these 3 cases, still plagued by the fact that the console prompt is not output on app exit? Is there a way to `force` this to happen?

**Comment by jasin** [comment]
Ok, I am having fun. But now I see one of the truths while doing experimentation. I wasn't sure I understood it till now. 

So since we understand the problem now the solution makes perfect sense. 
`start /WAIT test-con2.exe`

I guess the other solution in code is to send the `Enter` key to the parent console when it has focus NEXT. 

**EDIT:** in other words, we can't freeconsole() a console window that has already been freed by the child process.

**Comment by geoffmcl** [comment]
Hi @jasin,

Glad you are having fun! That is what it is
**all** about ;=))

You did **not** explain what you did **not** understand,  
until now, so no response to that...

If your solution to this problem is that the user 
should run another shell, then when that last shell
exits, the prompt will be printed? 

PAH! Is **not** a solutions... is a discovery? Is 
to be expected... what makes "perfect sense" about 
that?

> I guess the other solution in code...

Tried some things like that but did not work... 

Do you have a workable solution? Yes? No? Share...

> ... we can't freeconsole() ...

What rubbish is this? This is **only** done if the 
'attach` works...

> ... freed by the child process ...

Do you understand the term 'child process'? And that 
'child process' you refer to, would not delete a 
console it did not create... so what does "freed by the 
child process" mean, to you? What parent -> child do 
you refer to, see... please explain? Maybe I miss 
the point...

I feel sure there might be a way to trigger a prompt 
paint, after a program marked SUBSYSTEM:WINDOWS, that has
unusually attached to the current console, exits, 
but have not found it yet... 

For sure this is something about the fact that we 
`attached` to an existing console... 

How can our exit, when we free our attachment console, 
trigger a console prompt repaint?

To me, is still a very interesting question... thanks 
for your comments...

Regards,
Geoff.

PS: A small reminder, while I get every issue posted,
I do not get `edits`... Now you are free to edit your 
comment, at any time... no problem...

But just to repeat, the repo `owners` only gets the first 
post of an issue... and all new posts, and can therefore 
not yet see any subsequent **edits**, changes, new ideas 
on a current post...

But as one of the recipients of lots of emails, I would 
really prefer a new comment! A new email...

If the persons thought of something else, rather than edits, 
which I do not receive, until I visit the repo, I prefer a 
new comment posted...

Of course, it is always hoped a person adding a comment,
has pressed the **preview** button, and read it, at least 
once, before posting it... trying to avoid subsequent **edits**

But no problem, either way...

rgds, g

**Comment by jasin** [comment]
Yeah I did not get this one, but stumbled upon the answer unexpectedly while searching for a solution to the other problem. I inquired about his use of the 'hack' and he told me try it and see. Just read comments. Now I fully understand the problem freeconsole() doesn't solve. Took me a few days to check out what was happening, now I get it.

https://www.tillett.info/2013/05/13/how-to-create-a-windows-program-that-works-as-both-as-a-gui-and-console-application/

Anyway, to test this run test-con2.exe 2 ways. 
`test-con2.exe`
and
`start /WAIT test-con2.exe`
now compare the outputs from the time you press enter on the command till it is finished.

The question here is what does one want to accomplish I suppose? 
AttachConsole() = file redirection works, breaks freeconsole()
AllocConsole() = ensures console closes, breaks redirection

**Comment by geoffmcl** [comment]
@jasin you can run test-con2 **many** different ways... what has that got to do with this? Do not understand...

Here, we **only** discuss running it from a console... full stop...

accomplish: that a console prompt be printed on app exit, as it does in case 1... not in 2, 3, 4, ...

I can agree `AttachConsole` app should **not** use `FreeConsole`, a console it did **not** create... that seems **wrong**...

Just search for the correct `UnAttachconsole` API... something that signals I am exiting, done with the console, please re-print the prompt... nothing more...

Even all redirection in place, should now be flushed, and closed...

Maybe the impossible!!!

**Comment by jasin** [comment]
> I can agree AttachConsole app should not use FreeConsole, a console it did not create... that seems wrong...

**RED HERRING**
We are not calling DestroyConsole(), Nor did we actually AttachConsole().
Here in lies the problem. Since we are calling a /subsystem:WINDOWS app from a cosole window, Windows detaches the called (child) process from the parent console calling process before we, AttachConsole() back. **But we aren't actually attaching anything!!!!** imo The first misnomer.

If we actually did attach to the parent console, then when the child process exited the parent console would be aware of it and see the exit_code and re-paint the prompt as expected. It doesn't, so we know this is wrong by it's behavior...

as stated previous, to stop the way Windows works by default we have to force the parent calling console to /WAIT for an exit_code from called child process. Try it!!!! Once we tell the console window to wait, FreeConsole() works as intended, it is not a misnomer and it should not be a red herring and **destroy** anything!!!

That is how I see it. Am I wrong?

**Comment by geoffmcl** [comment]
Well, the one thing agreed is that there are 
maybe lots of **red herrings** hanging around ;=))

I re-read the `AttachConsole(ATTACH_PARENT_PROCESS)`,
and `FreeConsole()`, MSDN API and now think they **are**
a matching pair... the second is to undo the first... 
and should not be confused with `DestroyConsole`...

Really do not understand why you say **But we aren't 
actually attaching anything!!!!** HUH! Yes, it is a 
case of the cmd loader detaching the process from 
the console, and then we are `re-attaching` it, what 
ever **attaching** fully actually means...

To try to learn more, I added two things to test-con2... 
a -n to inhibit using `FreeConsole()`, and a -s nn, to 
delay nn seconds before app exit...

Yes, we can load a new console with `start`, and tell it 
to **wait** for the process to end, and that works... 
never said it wouldn't...

But this is not running it in the first console... this 
is running it in a second, that waits... maybe does not 
detach... etc... certainly possible, but not what is 
wanted...

And sure after I have now tested using my delay, and 
-n inhibitor, got to understand a little more, maybe 
test-con2 can **not** be fixed in this `prompt` regard! 

Maybe it **is** the stupid kludge it **is** ;=))

**Comment by jasin** [comment]
> But this is not running it in the first console... this 
> is running it in a second, that waits... maybe does not 
> detach... etc... certainly possible, but not what is 
> wanted...

you should try that and verify what you think happens. Because from the behavior I witness, this is not the case. There is no SECOND cmd.exe window when using /WAIT

**Comment by geoffmcl** [comment]
When I read `start /?` the first line says -

Starts a separate window to run a specificed program or command.

Now, if that program is subsystem:windows then of 
course there is no visible window created... it does 
not ask for one... so no console window is created...
the program can of course create all the windows it 
wants to display...

Is there a new `cmd.exe` loaded to do this... maybe not...
hopefully not...

We are already running inside a command processor... it 
could just create a new environment... invoke, in this 
case the exe loader, passing on the program, and wait 
for the exit... nothing else to do... sort of `lock` up...

Simply I do not want to pass on to my test-con2 immense 
users base, millions..., that this program is best run 
with `start /WAIT test-con2`... because...

Sure the only difference is -

```
1: test-con2 [options] redir
2: start /WAIT test-con2 [options] redir
```

That's **all** I am trying to say - I want it run 
as the first, **not** as the second... however 
that is all managed, handled, seen...

Well, it presently does all that... and it presently 
emulates its cousin, subsystem:console quite well...

Except for a relatively minor issue, namely displaying 
the prompt on exit, it does fine...

Yes, one way around this is the use the `start` 
command first... not my choice, but works...

But I do use the `start` command, in quite a number 
of scripts, usually to detach the program from 
the console where I am running say a build... I 
want it loaded in a separate window, like MSVC, so 
I can have my prompt back...

And there are other cases where I prefer, that the 
program I invoke should sort of 'lock' this console...
that is no command prompted printed until I exit 
that program...

So really think I tried that, and verified what I 
think is happening... and choose `no`, not in this 
case...

Maybe a witnesses only see what they want to see...

**Comment by jasin** [comment]
Alright, that is what I think to about `start`. But it **illustrates** the problem with AttachConsole(). 

That is what I am trying to say, there is a definitive compromise here you have to make. AFAIK it is **impossible** to unattach the console window when calling a /subsystem:WINDOWS app. and because you can't fully re-attach with that red herring AttachConsole(), then you have a brick wall.

For the end all crux of the problem, it is the **inability** to inform/control the parent calling console **after** you AttachConsole(). The only way to even remotely get this too work is to see what Daniel Tillet did. Press 'enter' for the user instead.  I'm not a fan, so maybe if file redirection is that much worth the effort? then you wouldn't care about ever needing to re-paint the command prompt because you always redirect it regardless.

**Comment by geoffmcl** [comment]
Thanks for reminding me of that [Daniel 
Tillet](https://www.tillett.info/2013/05/13/how-to-create-a-windows-program-that-works-as-both-as-a-gui-and-console-application/) link...

I had only glanced at it before, mostly agreed, but 
now re-read it carefully... I had missed the cute 
`sendEnterKey()`, provided you are still in the 
foreground...

Will just have to try that ;=))

Wow, talk about a mess, on a mess, on a mess, and now 
add even more **mess**... but might work...

And **all** this to save the auto creation of a **new** 
command prompt window, if **not** already run in one, 
that subsystem:console does, has...

But must see if this program "enter" key works?

**Comment by jasin** [comment]
> But must see if this program "enter" key works?

It works, I'll push!

**Comment by jasin** [comment]
[https://github.com/geoffmcl/test-console/tree/test](url)

I pushed to test branch

**Comment by geoffmcl** [comment]
@jasin looks good... 

But can you rebase `test` to latest `master`... you are presently 3 plus commits behind `master`... 

```
$ git checkout master
$ git pull
$ git checkout test
$ git rebase master
$ # fix any conflicts
$ git push
```

But as I say, looks good... thanks...

**Comment by geoffmcl** [comment]
View this graphic to show where [test](https://github.com/geoffmcl/test-console/network) is at the moment...

**Comment by jasin** [comment]
Well I ended up there. But I made one too many commits.
I thought I was ok though, as the rebase finished successful, I failed to check if it compiled first.

**Comment by jasin** [comment]
As an exercise I want to see if I can clean up my mess. Give me a few moments

**Comment by geoffmcl** [comment]
You correctly started this exercise in a `branch`... that is **always** a good move... following the above instructions to the letter would have just updated `test`, so it could be tested... all good...

Now you seem to be fiddling with `master`... ok, will wait and see...

**Comment by jasin** [comment]
What a Kudge, But I fixed it, I think. 
I went back to your last good commit
`dfefa4bbabbd2a4d7494e56602b3d141e81c6d4c`
and then applied my patch and pushed force to master.
Which means I probably broke your local branch master. 
**Hopefully you are still at your last good commit** and can just do
`git pull`

**Comment by geoffmcl** [comment]
Yes, looking at the git log all now looks 
fine in `master`... thanks... 

You were supposed to be rebasing `test`... oh, well, 
maybe you could now delete `test`-

```
$ git checkout master
$ git push origin :test
```

Note the `:` in front of test...

But now I note you have **removed** the 
`FreeConsole()` call??? **WHY?**

Of course I am not fully aware of all, everything that 
`AttachConsole(-1)` does, and then what `FreeConsole()` 
also fully does... but the API docs seem to match 
the two functions as a pair...

It may be that some things, like handles, are closed 
on program exit, but I can still not see the 
need to **not** do `FreeConsole()`... Explain?

From the commit log I can read maybe what you think -
"... Call sendEnterFunction to release console!"

Why would sending an enter key have anything 
to do with `releasing the console`? Seems conceptually 
wrong!

The only missing step from `test-con2` was re-painting 
the prompt, on app exit... no more... and to repeat 
the 4 cases -

```
1: test-con2 > temp1.txt 2>&1
2: test-con2 > temp2.txt
3: test-con2 2> temp3.txt
4: test-con2 
```

The prompt was repainted in case 1:... so how does 
this change effect that? I certainly hope there is not 
a duplicated prompt ... oops, it seems there is... bug!

And now, in cases 2:, 3:, 4:, I see one or all of 
`log_output(4)` and there should be none. This was 
after the `FreeConsole()`, so there should **not** 
be any valid std io handles available... bug!

Sort of one bug down, and two **new** bugs pop up ;=))

I think `FreeConsole()` has to come back!

And really, you should **not** change things without 
a discussion as to why... some agreement... unless in 
your own repo...

Me suggesting I wanted to try the `sendEnterKey()` does 
**not** mean I wanted **other** things **changed**!

So, who is to fix these two **new** bugs?

**Comment by jasin** [comment]
Well, I didn't remove it, just commented it out because I was not seeing it as useful. Maybe you found a use for it. I am not sure what you are expecting? I have yet to check the logs. I just pay attention to the cmd.exe window and prompt.

> Of course I am not fully aware of all, everything that 
> AttachConsole(-1) does, and then what FreeConsole() 
> also fully does... but the API docs seem to match 
> the two functions as a pair...

See, I am calling BS on this from an MSDN POV. What that documentation fails to explain is that you can not **free** a console that has already been **detached**. If the streams are still attached and FreeConsole() releases those streams from the console then by all means use it, but so would **exiting** the main app. Exiting the app would also close the streams that it **re-opened** and redirected. Still not sure if this is a big deal... Other then it seems to log to SPRTF file without FreeConsole() being called. <-- it is **impossible** to detach an already detached console (default /subsystem:WINDOWS behavior), Red herring. Which is why I called AttachConsole() a red herring. They don't do as the name fully suggest in the documentation.

> The prompt was repainted in case 1:... so how does 
> this change effect that? I certainly hope there is not 
> a duplicated prompt ... oops, it seems there is... bug!

**Yes** , this is what you end up with. This is the effect of fixing file redirection. You can not change this afaik using AttchConsole(). The problem is that /subsystem:Windows **ALWAYS** detaches and prints command prompt prior to any stream re-attachment. If only you could change this default hard coded behavior. But you can not!!!!

> So, who is to fix these two new bugs?

Fix (A) and (B) shows up. Fix (B) and (A) shows up. I am at the end, unless Microsoft changes and allows one to change default behavior of /subsystem:WINDOWS to stop the immediate detach there is nothing we can do to solve this. 

But I can certainly re-implement freeconsole(), no problem. But should we FreeConsole() before or after we release the console (Really release it, give command prompt back to user by way of emulating a enter key strike) I am thinking simply nested if statements.

```
if attached == yes
    Freeconsole()
    if console window in focus
        sendEnterKey()
```

**Comment by geoffmcl** [comment]
Well commenting something out **is** removing it... becomes 
a comment, rather than active code... but that is just stupid 
BS semantics...

And I do not know why you think the MSDN API is BS? I'll 
certainly agree it could say a lot more things... give a 
fuller, better, explanation of the actions of the API...

I hope we can get off the `red herrings` ;=)) Never 
really liked that particular fish... and still do not 
see how it could be applied to `AttachConsole(-1)`,
`FreeConsole()`, despite re-reading your raves several
times, in several posts...

`FreeConsole()`! You sort of ask if I found a use for 
it, but then go on with a good reason to do it ;=))

It frees those streams, such that in the test `log_output(4)` 
does **not** show in the console... YES, it is agreed they 
are also closed on app exit... but I prefer that tidying up 
be done by the app itself...

Like in the following code, I always prefer the app close 
a file when it is finished with it -

```
  FILE *fp = fopen("temp.txt","r");
  // read, and deal with data
  fclose(fp);   // YES, this is probably optional
  // well unless elsewhere "temp.txt" is opened,...
```

And you have already seen for instance that you can 
not delete, or rename files that are open (in windows),
so a good reason to get used to tidying up, always...

It is not a big deal, unless someone then tries to 
argue that there is no reason to do it... it will happen 
on app exit anyway... wants to promote untidy, unfinished 
code... laziness even... inattention to detail...

What type of coder does [s]he aspire to be? Sloppy, 
would be another word that applies...

Wow, this is certainly **not** fix (A) and (B) shows up... 
fix (B) and (A) shows up... Rubbish!

This was fix (A) and at the same time change something else,
(X), and (B) and (C) show up...

Duplicated prompt, new B, can be fixed by not sending a 
return if both stdout and stderr have been redirected.

Seeing the final `log_output(4)`, new C, can be fixed by 
**not** doing the removal of `FreeConsole()`, (the X change).

Ipso facto, fixing (B) and (C) will not bring back (A)!

Yes, the order in which things are done is probably 
important, and depends on testing, which is best, works,
etc...

If the sendEnterKey() still works after `FreeConsole()`,
then maybe it should be done after any `sleep_delay_secs`. 

That is really only as the app exits, if it was attached, 
and if the console window has focus, AND now (B), if 
**both** have not been redirected... when it is not 
required...

And the `FreeConsole()` should be a double if -
 if (attached && add_free_console)

As a test app, want to be able to turn it off, and 
observe, test, show the difference...

But, as usual, today is shopping and french, so will 
not get a chance to experiment, test, and learn the 
`best` way until later...

But if you get a chance between now and then, that 
would be good... or have you given up on this 
exploration?

**Comment by jasin** [comment]
My problem here is the use of the term **ATTACH**

I read the MSDN and AttachConsole() returns handles to the parent console window. Maybe some other things. But where did it actually Attach as the name **surely suggest**? 
One would assume, by reading the MSDN, that FreeConsole() was meant to release the console that was attached. But I ask again, what was actually attached?

Attach to it and use it exclusively, But this is not the case (because parent console is not waiting for our app to exit now, nothing is holding it exclusively to out running program). We haven't attached our app to console yet, it still does nothing even if we are asking std streams to do something.

_At this point in 'debug' mode. Our app is running. Parent console is **detached** (MSW words, not mine) and the console is now free to take input to cmd.exe and execute it. See below._ 

This leads me to  the impression that since we don't have exclusive control, what stops someone else from attaching to said console and redirecting it's std streams to that console? 
The console is not waiting for an exit code, so there is nothing telling the console window to not do as we ask it to do...

_in debug mode. Our App is now quote on quote **attached** to parent console and streams are re-opened/directed to parent console._

why couldn't you do this then now?
IE. put test-con2 into a loop and then start test-con2 again from parent console. Windows has already released the console and nothing has exclusive control over it, it should be ready to run another app <--possible??? I think so, if stdin has not been redirected to parent console. Input to parent console now is read by cmd.exe and executed
I do not like this can of worms.

Yes, we should always be tidy. But there should be no need to call FreeConsole() unless you attach the streams to parent console handles. But I am firmly on the fence now with whether that should or should not be done with the streams when calling AttachConsole(). AttachConsole() was meant to fix redirection in my case, but I am having trouble with using it to redirect std streams back to parent console window.

**Comment by jasin** [comment]
[test2 Branch](https://github.com/geoffmcl/test-console/tree/test2)

Should fix the issue w/ problem (X), verify?

**Comment by geoffmcl** [comment]
Rather than challenging, questioning, understanding, your many 
`words`, `ideas`, `phrases`, `understanding`, 'nuances', and 
your reading of the MSDN API, etc, etc, ... you gave me a 
**sample** to try... 

I prefer exploring that... thanks...

Words are nothing... working code says it all to me... code 
not yet actually reviewed...

REPORT: Testing `test2` branch...

Test 1: run `test-con2 > temp1.txt 2>&1`

Console scrape:

```
F:\Projects\test-console\buildt>release\test-con2 >temp1.txt 2>&1

F:\Projects\test-console\buildt>
F:\Projects\test-console\buildt>
```

That is near perfect. No redirection in place, so we see nothing,
except the prompt... and we do not see the `log_output(4);` 
output, done after everything should be closed... bug (C) gone...

We see the prompt The first time since it is a subsystem:windows 
app, so it is detached from the console, so we get a prompt 
printed. That is normal, understood...

Oops, where did that second prompt come from? Could we, with 
**more mess** even avoid that?

Seems this bug (B) is still there!

Can this be **fixed** with even more kludge WIN32 only code?

I think so... and should be done, if only for understanding...

Test 2: run `test-con2 > temp1.txt`

Console scrape:

```
F:\Projects\test-console\buildt>release\test-con2 > temp1.txt

F:\Projects\test-console\buildt>test-con2:3: Output to stderr

F:\Projects\test-console\buildt>
```

That also seems near perfect. We redirected stdout, so that does 
not appear... and at exit the prompt appears...

Good result.

Test 3: run `test-con2 2> temp1.txt`

Console scrape:

```
F:\Projects\test-console\buildt>release\test-con2 2> temp1.txt

F:\Projects\test-console\buildt>
test-con2: AttachConsole succeeded... stdout: Done fropen, stderr: is disk file
Info:
HOut is FILE_TYPE_UNKNOWN (type 0) - handle: 000000000000000B (-11)
HErr is FILE_TYPE_DISK (type 1) - handle: 000000000000006C (-12)
HIn  is FILE_TYPE_UNKNOWN (type 0) - handle: 0000000000000003 (-10)
test-con2:3: Output to stdout
test-con2: Doing FreeConsole() call...

F:\Projects\test-console\buildt>
```

Also quite perfect. We see the console prompt immediately, because 
a subsystem:windows app is detached by the loader from the current 
active console, if there is one...

And we see the second after the app exit... looks quite good!

Good result.

4: run `test-con2`

Console output: 

```
F:\Projects\test-console\buildt>release\test-con2

F:\Projects\test-console\buildt>
test-con2: AttachConsole succeeded... stdout: Done fropen, stderr: Done fropen
Info:
HOut is FILE_TYPE_UNKNOWN (type 0) - handle: 0000000000000007 (-11)
HErr is FILE_TYPE_UNKNOWN (type 0) - handle: 000000000000000B (-12)
HIn  is FILE_TYPE_UNKNOWN (type 0) - handle: 0000000000000003 (-10)
test-con2:3: Output to stdout
test-con2:3: Output to stderr
test-con2: Doing FreeConsole() call...

F:\Projects\test-console\buildt>
```

So this also is very correct. No redirection in place... All `stdout` 
and `stderr` seen... thanks to using `freopen`...

After the program header reads the EXE subsystem type, it detaches 
the console, and we see the prompt... then `test-con2` begins,
and all of its stdout and stderr are seen...

Then on exit, the prompt is printed again. All very **good**!

NOTE: In all tests here have yet to fully review the LOG file,
tempex.txt, but in this case do **not** think it will add any 
information...

Re: Results

This was done without even looking at the code. 

And except for the unnecessary duplicated prompt, ie new bug (B), 
all seems very **good**... thanks...

Of course I have not yet tried a `-s 10` second delay... Will the 
order, and the results stay the same? 

We will have to wait an see...

But this `test2` branch, so far, in minimal testing, has solved most 
things... just continues with the (B) bug, not a big thing... 
but if it can be avoided, all to the better...

Tomorrow, will review the actual code.. **AND** add the `-s 15` tests... 
and if all is well, maybe this can be **closed**...

Really, thanks for your continued support on this...

**Comment by jasin** [comment]
> I think so... and should be done, if only for understanding...

Done. Passes -s test too

**Comment by jasin** [comment]
@geoffmcl Just curious if you got a chance to check this out? What other issues are left that we can try and massage to make this more appealing?

**Comment by geoffmcl** [comment]
Appear to have solved most/some of this in `test-con3`, but still more testing needed... but meantime closing this...
